name: create draft

on:
  workflow_dispatch:
    inputs:
      title:
        description: "Title"
        required: true

jobs:
  create-draft:
    uses: hatena/hatenablog-workflows/.github/workflows/create-draft.yaml@c07e5aa45846c02b1f297e28bc519da50081a31c # v2.0.8
    with:
      title: ${{ github.event.inputs.title }}
      draft: true
      BLOG_DOMAIN: ${{ vars.BLOG_DOMAIN }}
    secrets:
      OWNER_API_KEY: ${{ secrets.OWNER_API_KEY }}
