name: pull from hatenablog

on:
  workflow_dispatch:

jobs:
  pull:
    uses: hatena/hatenablog-workflows/.github/workflows/pull.yaml@c07e5aa45846c02b1f297e28bc519da50081a31c # v2.0.8
    with:
      BLOG_DOMAIN: ${{ vars.BLOG_DOMAIN }}
    secrets:
      OWNER_API_KEY: ${{ secrets.OWNER_API_KEY }}
