name: pull draft from hatenablog

on:
  workflow_dispatch:
    inputs:
      title:
        description: "Draft Entry Title"
        required: true

jobs:
  pull-draft:
    uses: hatena/hatenablog-workflows/.github/workflows/pull-draft.yaml@aa2df9dc72675704d8f7291c874a36cc02807955 # v2.0.9
    with:
      title: ${{ github.event.inputs.title }}
      draft: true
      BLOG_DOMAIN: ${{ vars.BLOG_DOMAIN }}
    secrets:
      OWNER_API_KEY: ${{ secrets.OWNER_API_KEY }}
