name: push published entries


on:
  pull_request:
    paths:
      - "entries/**"

jobs:
  push-published-entries:
    uses: hatena/hatenablog-workflows/.github/workflows/push-published-entries.yaml@fa544a63e845030ff65e35d78847e2bc2cab981e # v2.0.2
    secrets:
      OWNER_API_KEY: ${{ secrets.OWNER_API_KEY }}
