name: push published entries


on:
  pull_request:
    paths:
      - "entries/**"

jobs:
  push-published-entries:
    uses: hatena/hatenablog-workflows/.github/workflows/push-published-entries.yaml@c07e5aa45846c02b1f297e28bc519da50081a31c # v2.0.8
    secrets:
      OWNER_API_KEY: ${{ secrets.OWNER_API_KEY }}
