name: push to hatena blog

on:
  pull_request:
    branches:
      - main
    types: [closed]
    paths:
      - "entries/**"

jobs:
  push:
    uses: hatena/hatenablog-workflows/.github/workflows/push.yaml@c66dc4d14ac849b7d82e7097eaf9d02485eefb71 # v2.1.1
    with:
      local_root: "entries"
    secrets:
      OWNER_API_KEY: ${{ secrets.OWNER_API_KEY }}
