name: push to hatena blog

on:
  pull_request:
    branches:
      - main
    types: [closed]
    paths:
      - "entries/**"

jobs:
  push:
    uses: hatena/hatenablog-workflows/.github/workflows/push.yaml@aa2df9dc72675704d8f7291c874a36cc02807955 # v2.0.9
    with:
      local_root: "entries"
    secrets:
      OWNER_API_KEY: ${{ secrets.OWNER_API_KEY }}
