name: push draft to hatena blog

on:
  pull_request:
    paths:
      - "draft_entries/**"

jobs:
  push-draft:
    uses: hatena/hatenablog-workflows/.github/workflows/push-draft.yaml@aa2df9dc72675704d8f7291c874a36cc02807955 # v2.0.9
    secrets:
      OWNER_API_KEY: ${{ secrets.OWNER_API_KEY }}
