name: push draft to hatena blog

on:
  pull_request:
    paths:
      - "draft_entries/**"

jobs:
  push-draft:
    uses: hatena/hatenablog-workflows/.github/workflows/push-draft.yaml@c66dc4d14ac849b7d82e7097eaf9d02485eefb71 # v2.1.1
    secrets:
      OWNER_API_KEY: ${{ secrets.OWNER_API_KEY }}
