name: push published entries


on:
  pull_request:
    paths:
      - "entries/**"

jobs:
  push-published-entries:
    uses: hatena/hatenablog-workflows/.github/workflows/push-published-entries.yaml@c66dc4d14ac849b7d82e7097eaf9d02485eefb71 # v2.1.1
    secrets:
      OWNER_API_KEY: ${{ secrets.OWNER_API_KEY }}
