name: push when publishing from draft

on:
  pull_request:
    branches:
      - main
    types: [closed]
    paths:
      - "draft_entries/**"

jobs:
  push-when-publishing-from-draft:
    uses: hatena/hatenablog-workflows/.github/workflows/push-when-publishing-from-draft.yaml@c66dc4d14ac849b7d82e7097eaf9d02485eefb71 # v2.1.1
    with:
      BLOG_DOMAIN: ${{ vars.BLOG_DOMAIN }}
    secrets:
      OWNER_API_KEY: ${{ secrets.OWNER_API_KEY }}
