name: push when publishing from draft

on:
  pull_request:
    branches:
      - main
    types: [closed]
    paths:
      - "draft_entries/**"

jobs:
  push-when-publishing-from-draft:
    uses: hatena/hatenablog-workflows/.github/workflows/push-when-publishing-from-draft.yaml@c07e5aa45846c02b1f297e28bc519da50081a31c # v2.0.8
    with:
      BLOG_DOMAIN: ${{ vars.BLOG_DOMAIN }}
    secrets:
      OWNER_API_KEY: ${{ secrets.OWNER_API_KEY }}
