name: push when publishing from draft

on:
  pull_request:
    branches:
      - main
    types: [closed]
    paths:
      - "draft_entries/**"

jobs:
  push-when-publishing-from-draft:
    uses: hatena/hatenablog-workflows/.github/workflows/push-when-publishing-from-draft.yaml@fa544a63e845030ff65e35d78847e2bc2cab981e # v2.0.2
    with:
      BLOG_DOMAIN: ${{ vars.BLOG_DOMAIN }}
    secrets:
      OWNER_API_KEY: ${{ secrets.OWNER_API_KEY }}
